from . import student
from . import student_admission
from . import student_document
from . import student_registration
from . import student_attendance
from . import student_id_card
from . import student_parent
from . import student_discipline
from . import student_ledger
from . import student_seat_blocking
from . import student_enquiry
from . import student_counselling_session
from . import student_assignment
from . import student_assignment_submission
from . import student_assignment_grading