from . import faculty
from . import faculty_attendance
from . import faculty_attendance_regularization
from . import faculty_designation
from . import faculty_evaluation
from . import faculty_leave
from . import faculty_salary
from . import faculty_workload
from . import zk_faculty_bridge
from . import faculty_form16