from . import admission
from . import attendance
from . import fees
from . import hall_ticket
from . import id_card
from . import placements
from . import promotion
from . import registration
from . import result
from . import iic
from . import naac
from . import date_range
from . import examination
from . import nba
from . import asset