from . import classes
from . import parent
from . import student
from . import student_document
from . import subject
from . import teacher
from . import exam
from . import exam_result
from . import library
from . import library_issue
from . import transport
from . import fee
from . import hostel
from . import fee_type