{
    "name": 'IT Inventory & Asset Management',
    "version": '18.0.1.0.0',
    "summary": 'Manage and track IT assets such as laptops, desktops, servers, and peripherals.',
    "description": 'Track and manage IT assets such as computers, servers, and related equipment. Supports asset assignment, maintenance, and lifecycle monitoring.',   
    'category': 'Inventory',
    "version": "18.0",
    "author": "Techinfini Solutions Pvt. Ltd.",
    "maintainer": "Techinfini Solutions Pvt. Ltd.",
    "company" : "Techinfini Solutions Pvt. Ltd.",
    "contributor": "Yash Suvta, Mayur Kukreja, Nitin Upmanyu",
    'website': 'https://www.techinfini.in/',
    "support": "https://www.techinfini.in/contact/",
    "depends": ['contacts'],
    'post_init_hook': 'create_dashboard_block',
    "data": [
        'security/it_inventory_and_asset_management_security.xml',
        'security/ir.model.access.csv',
        'views/asset_brand.xml',
        'views/asset_type.xml',
        'views/asset_model.xml',
        'views/it_assets.xml',
        'views/it_components.xml',
        'views/dynamic_block_views.xml',
        'views/system_system.xml',
        'views/res_partner.xml',
        'views/menus.xml',
    ],
    "assets": {
        'web.assets_backend': [
            'it_inventory_and_asset_management/static/src/css/dynamic_dashboard.css',
            'it_inventory_and_asset_management/static/src/scss/dynamic_dashboard.scss',
            'it_inventory_and_asset_management/static/src/xml/dynamic_dashboard_template.xml',
            'it_inventory_and_asset_management/static/src/xml/order_stats_tile.xml',
            'it_inventory_and_asset_management/static/src/js/dynamic_dashboard_tile.js',
            'it_inventory_and_asset_management/static/src/js/dynamic_dashboard_chart.js',
            'it_inventory_and_asset_management/static/src/js/order_stats_tile.js', 
            'it_inventory_and_asset_management/static/src/js/dynamic_dashboard.js',    
        ],
    },
    "license": "OPL-1",
    "installable": True,
    "application": False,
    "auto_install": False,
    'images': ['static/description/IT Inventory & Asset Management.gif'],
}