from . import hostel
from . import hostel_allocation
from . import hostel_attendance
from . import hostel_complaint
from . import hostel_mess
from . import hostel_room
from . import hostel_visitor
from . import mess_attendance
from . import mess_feedback
from . import mess_item
from . import mess_menu