{
    'name': 'Library Management',
    'version': '1.0',
    'summary': 'Manage library books, authors, borrowings, and members',
    'depends': ['base', 'mail', 'web'],
    'data': ['security/ir.model.access.csv',
             'views/book_views.xml',
             'views/author_views.xml',
             'views/category_views.xml',
             'views/member_views.xml',
             'views/borrowing_views.xml',
             'reports/library_reports.xml',
             'reports/library_report_templates.xml',
             'data/cron_jobs.xml',
             'data/email_templates.xml',
             ],
    'installable': True,
    'application': True,
}
