from . import main
from . import id_card_controller
from . import hall_ticket_controller
from . import marksheet_controller
from . import student_portal
from . import parent_portal
from . import faculty_portal
from . import alumni_portal
from . import iic_portal
from . import iic_poster_controller
from . import naac_dashboard_api
from . import naac_evidence_controller
from . import portal_fee
from . import asset_qr_controller
from . import library_opac_controller
from . import online_exam_controller
from . import ai_assistant