from . import it_components
from . import it_assets
from . import asset_type
from . import asset_model
from . import asset_brand
from . import used_user_logs
from . import dashboard_block
from . import domain_to_sql
from . import system_system
from . import res_partner