from . import academic
from . import student
from . import fee
from . import examination
from . import faculty
from . import library
from . import hostel
from . import transport
from . import placement
from . import alumni
from . import project
from . import internship
from . import events
from . import timetable
from . import dashboard
from . import resusers
from . import resconfig
from . import iic
from . import naac
from . import asset
from . import nba